-- MySQL Script generated by MySQL Workbench
-- Mon May 24 10:30:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario` (
  `idtb_usuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtb_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_grupos` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tema` VARCHAR(45) NOT NULL,
  `fk_tb_usuario_criador` INT NOT NULL,
  PRIMARY KEY (`id_grupo`),
  INDEX `fk_tb_grupos_tb_usuario_idx` (`fk_tb_usuario_criador` ASC) VISIBLE,
  CONSTRAINT `fk_tb_grupos_tb_usuario`
    FOREIGN KEY (`fk_tb_usuario_criador`)
    REFERENCES `mydb`.`tb_usuario` (`idtb_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_postagem` (
  `id_postagem` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `url_postagem` VARCHAR(145) NULL,
  `fk_grupos_criador` INT NOT NULL,
  `tb_usuario_criador` INT NOT NULL,
  PRIMARY KEY (`id_postagem`),
  INDEX `fk_tb_postagem_tb_grupos1_idx` (`fk_grupos_criador` ASC) VISIBLE,
  INDEX `fk_tb_postagem_tb_usuario1_idx` (`tb_usuario_criador` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagem_tb_grupos1`
    FOREIGN KEY (`fk_grupos_criador`)
    REFERENCES `mydb`.`tb_grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagem_tb_usuario1`
    FOREIGN KEY (`tb_usuario_criador`)
    REFERENCES `mydb`.`tb_usuario` (`idtb_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_inscritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_inscritos` (
  `fk_usuario_inscrito` INT NOT NULL,
  `fk_grupos_inscrito` INT NOT NULL,
  PRIMARY KEY (`fk_usuario_inscrito`, `fk_grupos_inscrito`),
  INDEX `fk_tb_usuario_has_tb_grupos_tb_grupos1_idx` (`fk_grupos_inscrito` ASC) VISIBLE,
  INDEX `fk_tb_usuario_has_tb_grupos_tb_usuario1_idx` (`fk_usuario_inscrito` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_has_tb_grupos_tb_usuario1`
    FOREIGN KEY (`fk_usuario_inscrito`)
    REFERENCES `mydb`.`tb_usuario` (`idtb_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_has_tb_grupos_tb_grupos1`
    FOREIGN KEY (`fk_grupos_inscrito`)
    REFERENCES `mydb`.`tb_grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_comentario` (
  `id_comentario` INT NOT NULL,
  `comentario` VARCHAR(155) NULL,
  `fk_postagem` INT NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_tb_comentario_tb_postagem1_idx` (`fk_postagem` ASC) VISIBLE,
  CONSTRAINT `fk_tb_comentario_tb_postagem1`
    FOREIGN KEY (`fk_postagem`)
    REFERENCES `mydb`.`tb_postagem` (`id_postagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
